=== WindarLobo/1_Dam/LenguajesDeMarcas/Evaluacion_2/boletin25/boletin25.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!--Ejercicio 1-
<xs:element name="zapatos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="zapato" type="xs:string"/>
        <xs:element name="color">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="negro"/>
                     <xs:enumeration value="azul"/>
              <xs:enumeration value="marron"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>-->
  
  <!--Ejercicio 2-
   <xs:element name="usuario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombreUsuario" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      
        <xs:element name="claveUsuario">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:length value ="7"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      
      </xs:sequence>
    </xs:complexType>
  </xs:element>-->
  

    <!--Ejercicio 3-
  <xs:element name="usuario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombreUsuario" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="claveUsuario">
          <xs:simpleType>
            <xs:restriction base="xs:string">
             <xs:minLength value="5"/>
              <xs:maxLength value="9"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>-->
      <!--Ejercicio 4-

  <xs:element name="fichero">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="nombreFichero">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value ="[a-zA-Z0-9]{8}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
        <xs:element name="extension">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value ="xml||xsd"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>-->
  
        <!--Ejercicio 5-
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="alumno" maxOccurs="2">
          <xs:complexType>
      <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="direccion">
      <xs:complexType>
      <xs:sequence>
      
        <xs:element name="calle" type="xs:string" />
        <xs:element name="numero" type="xs:string" />
         <xs:element name="ciudad" type="xs:string" />
          <xs:element name="provincia" type="xs:string" />
      
      </xs:sequence>
      </xs:complexType>
      </xs:element>
      
       <xs:element name="telefono" >
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:length value ="9"/>
              
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        
</xs:sequence>
<xs:attribute name="dni " type="xs:string" use="required"/>
</xs:complexType>
</xs:element>
 
 </xs:sequence>
          </xs:complexType>
          </xs:element>-->
          
      <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
      <xs:sequence>
      <xs:element name="titulo" type="xs:string" />
       <xs:element name="autor" type="xs:string"  maxOccurs="2"/>
        <xs:element name="fecha" type="xs:string" />
      
        <xs:element name="isbn">
        <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:length value ="10"/>
              </xs:restriction>
              </xs:simpleType>
            </xs:element>
    
        <xs:element name="editor" type="xs:string" />
        
      <xs:element name="categoria" >
        <xs:simpleType>
         <xs:restriction base="xs:string">
              <xs:pattern value ="ficcion|no ficcion "/>
              </xs:restriction>
              </xs:simpleType>
        </xs:element>
        
        <xs:element name="stock" type="xs:boolean" />
      </xs:sequence>
      <xs:attribute name="revisor " type="xs:string" use="optional"/>
      </xs:complexType>
      </xs:element>
      </xs:sequence>
      </xs:complexType>
      </xs:element>
      </xs:schema>

=== WindarLobo/1_Dam/LenguajesDeMarcas/Evaluacion_2/boletin25/boletin25.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Ejercicio 1-
<zapatos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd">
  <zapato>Mocasín</zapato>
  <color>negro</color>
</zapatos>-->

<!--Ejercicio 2-
<usuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd">
  <nombreUsuario>Martina García</nombreUsuario>
  <claveUsuario>win18lg</claveUsuario>
</usuario>-->

<!--Ejercicio 3-

<usuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd">
  <nombreUsuario>Martina García</nombreUsuario>
  <claveUsuario>12windar1</claveUsuario>
</usuario>-->

<!--Ejercicio 4-

<fichero xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd">
  <nombreFichero>win12Ada</nombreFichero>
  <extension>xml</extension>
</fichero>-->

<!--Ejercicio 5-

<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd"> 
<alumno dni="5656454">
<nombre>Juan Garcia</nombre>
<direccion>
<calle>Avenida de la Fuente</calle>
<numero>6</numero>
<ciudad>pontevedra</ciudad>
<provincia>tomiño</provincia>
</direccion>
<telefono>924555555</telefono></alumno>
<alumno dni="y3778564a">
<nombre>Jose Sanchez</nombre>
<direccion>
<calle>Calle Ancha</calle>
<numero>3</numero>
<ciudad>pontevedra</ciudad>
<provincia>.vigo</provincia>
</direccion>
<telefono>924550000</telefono>
</alumno>
</alumnos>-->

      
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam1/Documentos/lenguajes%20de%20marcas/evaluacion_2/boletin25/boletin25.xsd"> 
<libro >
<titulo>Los hombres que no amaban a las  mujeres</titulo>
<autor>Stieg Larsson</autor>
<fecha>2008</fecha>
<isbn>978-84-233</isbn>
<editor>Destino</editor>
<categoria>ficcion</categoria>
<stock>true</stock>
</libro>
<libro revisor="Luis Rodrigo">
<titulo>ava a través de los tiempos</titulo>
<autor>Jesús Bobadilla</autor>
<autor>Adela Sancho</autor>
<fecha>2003</fecha>
<isbn>978-84-567</isbn>
<editor>Ra-Ma</editor>
<categoria>ficcion</categoria>
<stock>false</stock>
</libro>
</libros>
